# MongoDB Shard 2 Configuration (Worker Node 2)
# Stores partition 2 of the network security logs

systemLog:
  destination: file
  path: /var/log/mongodb/shard2.log
  logAppend: true

storage:
  dbPath: /data/shard2

net:
  port: 27028
  bindIp: 0.0.0.0

sharding:
  clusterRole: shardsvr

replication:
  replSetName: shard2ReplSet
