# MongoDB Shard 1 Configuration (Worker Node 1)
# Stores partition 1 of the network security logs

systemLog:
  destination: file
  path: /var/log/mongodb/shard1.log
  logAppend: true

storage:
  dbPath: /data/shard1

net:
  port: 27018
  bindIp: 0.0.0.0

sharding:
  clusterRole: shardsvr

replication:
  replSetName: shard1ReplSet
